; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino


; PSRAM核心配置（关键）
board_build.arduino.memory_type = qio_opi  ; 内存类型：QIO+OPI（适配ESP32-S3的PSRAM）
board_build.flash_mode = qio               ; Flash模式：QIO
board_build.psram_type = opi               ; PSRAM类型：OPI（8MB PSRAM对应OPI模式）

; Flash容量配置
board_upload.flash_size = 16MB             ; Flash总容量16MB
board_upload.maximum_size = 16777216       ; 16MB对应的字节数（16*1024*1024）
board_build.partitions = default_16MB.csv  ; 16MB Flash对应的分区表

; 启用PSRAM编译宏
board_build.extra_flags = -DBOARD_HAS_PSRAM

lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit GFX Library@^1.12.4
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.12.3

; Serial Monitor options
monitor_speed = 115200